historical_flight_data_html_file_path = 'historical-data/historical-flight-data/html-download-website/html.txt'
historical_flight_data_html_file_path_int = 'historical-data/historical-flight-data/html-download-website/html-int.txt'
historical_flight_data_downloaded_file_path = 'historical-data/historical-flight-data/raw'
historical_flight_data_base_domain = 'https://www.bts.gov'
historical_flight_data_label_file_path = 'historical-data/historical-flight-data/html-download-website/column-titles.csv'